/**
 * SpecOps plugin entry point.
 *
 * On load, this module:
 * 1. Ensures the user-editable agent manifest exists at
 *    `~/.config/opencode/specops-manifest.json`. If missing, writes the
 *    built-in default from `manifest.ts`. If present, the user's file wins
 *    (their edits persist across plugin updates).
 * 2. Re-exports the SpecOps plugin and its default `PluginModule` export so
 *    OpenCode can load the package via `"plugin": ["@jrpbuilds/specops"]`.
 * 3. Augments the plugin's `config()` hook to register all 19 worker agents
 *    from the persisted manifest, with inline prompts generated by `prompts.ts`.
 *
 * The manifest file is intentionally NOT included in OpenCode's main config —
 * it lives in a known, stable location so users can edit agent models and
 * permissions without losing their changes on plugin updates.
 */

import type { Config } from "@opencode-ai/plugin"
import { mkdir, readFile, writeFile } from "node:fs/promises"
import os from "node:os"
import path from "node:path"
import { DEFAULT_MANIFEST, type SpecOpsManifest } from "./manifest.js"
import { promptText } from "./prompts.js"
import { SpecOpsPlugin } from "./orchestrator.js"

/**
 * The absolute path to the persisted user-editable agent manifest.
 *
 * Lives under `~/.config/opencode/` so it survives `npm update` of the
 * `@jrpbuilds/specops` package. The file is created on first load and never
 * overwritten by the plugin afterwards — user edits always win.
 */
export const MANIFEST_PATH = path.join(
  os.homedir(),
  ".config",
  "opencode",
  "specops-manifest.json",
)

/**
 * Load the agent manifest from {@link MANIFEST_PATH}, creating it from
 * {@link DEFAULT_MANIFEST} on first run.
 *
 * The manifest has no `$schema` field (kept minimal). Users edit it directly
 * to customize agent models, maxSteps, tools, and permissions; those edits
 * persist across plugin updates because the plugin never overwrites an
 * existing file.
 *
 * @returns The manifest to use for agent registration.
 */
export async function loadOrInitManifest(): Promise<SpecOpsManifest> {
  try {
    const content = await readFile(MANIFEST_PATH, "utf-8")
    const parsed = JSON.parse(content) as SpecOpsManifest
    if (parsed && typeof parsed === "object" && parsed.agents) {
      return parsed
    }
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== "ENOENT") {
      // Corrupt manifest: fall through to re-create the default. We do not
      // throw because a broken manifest should not crash OpenCode startup.
    }
  }
  // First run (or corrupt manifest): write the default so the user has a
  // stable, editable file. We intentionally do NOT overwrite an existing file
  // that parsed successfully — even if it's missing agents — so user edits win.
  await mkdir(path.dirname(MANIFEST_PATH), { recursive: true })
  await writeFile(
    MANIFEST_PATH,
    JSON.stringify(DEFAULT_MANIFEST, null, 2) + "\n",
    "utf-8",
  )
  return DEFAULT_MANIFEST
}

/**
 * The augmented SpecOps plugin.
 *
 * Wraps {@link SpecOpsPlugin} so the `config()` hook additionally registers all
 * 19 worker agents from the persisted manifest. The two controllers are
 * already registered by the inner plugin; the workers are added here so the
 * manifest (the user-editable source of truth) drives their definitions.
 *
 * Each worker is registered with `??=` so any agent the user has already
 * defined in their `opencode.json` is preserved — the plugin only fills in
 * missing agents.
 */
export const SpecOpsPluginWithManifest = (async (input: Parameters<typeof SpecOpsPlugin>[0]) => {
  const inner = await SpecOpsPlugin(input)
  const manifest = await loadOrInitManifest()
  return {
    ...inner,
    config: async (openCodeConfig: Config) => {
      await inner.config?.(openCodeConfig)
      openCodeConfig.agent ??= {}
      for (const [agentId, definition] of Object.entries(manifest.agents)) {
        // `??=` preserves any user override already present in opencode.json.
        openCodeConfig.agent[agentId] ??= {
          mode: "subagent",
          model: definition.model,
          maxSteps: definition.maxSteps,
          tools: definition.tools,
          permission: definition.permission,
          prompt: promptText(agentId),
        }
      }
    },
  }
}) as typeof SpecOpsPlugin

/**
 * The default export consumed by OpenCode when the package is listed in
 * `opencode.json`'s `plugin` array. The `id` matches the package name and the
 * `server` is the augmented plugin with manifest-driven agent registration.
 */
export default {
  id: "specops",
  server: SpecOpsPluginWithManifest,
} satisfies import("@opencode-ai/plugin").PluginModule

/** Re-export the manifest path and loader for tools, tests, and the sync script. */
export { DEFAULT_MANIFEST, promptText, SpecOpsPlugin }
export type { SpecOpsManifest }
